import { AdminDashboardDto, DashboardDto, MemberProfileDto } from './api-client'

const now = Date.now()
const day = 86400000

export const demoDashboard: DashboardDto = {
  community: {
    id: 1,
    name: 'Builder Circle',
    handle: '@buildercircle',
    description: 'A focused Telegram community for builders shipping every week.',
    status: 'active',
  },
  setup: [
    { id: 'profile', title: 'Create community profile', detail: 'Name, handle, description, and public positioning are ready.', status: 'done' },
    { id: 'telegram', title: 'Connect Telegram group', detail: 'Bot is admin in the premium group and can approve access.', status: 'done' },
    { id: 'plan', title: 'Create paid plan', detail: 'Pro monthly membership is live with Stars checkout.', status: 'done' },
    { id: 'referral', title: 'Launch referral loop', detail: 'Invite 3 members to unlock bonus sessions.', status: 'active' },
    { id: 'reward', title: 'Create first reward', detail: 'Founder and contributor badges are ready.', status: 'done' },
    { id: 'launch', title: 'Launch community', detail: 'Review access issues before opening the next cohort.', status: 'locked' },
  ],
  metrics: {
    healthScore: 82,
    members: 328,
    activeSubscriptions: 186,
    pendingRenewals: 2,
    referralActivations: 42,
    monthlyRevenueCents: 412900,
    monthlyStars: 14820,
    xpIssued: 18420,
    accessIssues: 3,
    productsSold: 37,
  },
  healthSignals: [
    { id: 1, title: 'Access queue needs attention', detail: '3 members paid or joined but do not have clean Telegram access yet.', tone: 'warn' },
    { id: 2, title: 'Referral loop is converting', detail: '42 activated members came through member invites this month.', tone: 'ok' },
    { id: 3, title: 'Weekly report is ready', detail: 'AI found 5 high-value topics from recent community activity.', tone: 'info' },
  ],
  nextActions: [
    { id: 'access-review', title: 'Review access queue', detail: 'Grant or repair 3 pending members.', target: 'access', priority: 'high' },
    { id: 'renewal-followup', title: 'Fix failed renewals', detail: '2 members need payment follow-up before access expires.', target: 'members', priority: 'high' },
    { id: 'campaign', title: 'Publish referral campaign', detail: 'Invite 3 friends unlocks bonus founder call.', target: 'growth', priority: 'medium' },
    { id: 'product', title: 'Create premium download', detail: 'Turn the onboarding checklist into a paid asset.', target: 'more', priority: 'low' },
  ],
  members: [
    {
      id: 1,
      username: 'deepa',
      role: 'owner',
      accessStatus: 'granted',
      source: 'direct',
      xp: 2480,
      level: 5,
      subscriptionStatus: 'active',
      planName: 'Founder',
      joinedAt: new Date(now - day * 42).toISOString(),
      lastActiveAt: new Date(now - 1000 * 60 * 12).toISOString(),
      revenueCents: 9900,
      referralCount: 11,
    },
    {
      id: 2,
      username: 'mira',
      role: 'member',
      accessStatus: 'granted',
      source: 'referral',
      xp: 940,
      level: 3,
      subscriptionStatus: 'active',
      planName: 'Pro',
      joinedAt: new Date(now - day * 9).toISOString(),
      lastActiveAt: new Date(now - day).toISOString(),
      revenueCents: 5800,
      referralCount: 4,
    },
    {
      id: 3,
      username: 'sam',
      role: 'member',
      accessStatus: 'pending',
      source: 'challengehub',
      xp: 260,
      level: 2,
      subscriptionStatus: 'trialing',
      planName: 'Trial',
      joinedAt: new Date(now - day * 2).toISOString(),
      lastActiveAt: null,
      revenueCents: 0,
      referralCount: 0,
    },
    {
      id: 4,
      username: 'nora',
      role: 'member',
      accessStatus: 'failed',
      source: 'paid',
      xp: 1720,
      level: 4,
      subscriptionStatus: 'past_due',
      planName: 'Pro',
      joinedAt: new Date(now - day * 20).toISOString(),
      lastActiveAt: new Date(now - day * 4).toISOString(),
      revenueCents: 8700,
      referralCount: 2,
    },
  ],
  chats: [
    {
      id: 1,
      title: 'Builder Circle Premium',
      handle: '@buildercircle_pro',
      type: 'group',
      botStatus: 'admin',
      accessMode: 'join_request',
      activeMembers: 186,
    },
    {
      id: 2,
      title: 'Builder Circle Updates',
      handle: '@buildercircle_updates',
      type: 'channel',
      botStatus: 'missing_permissions',
      accessMode: 'invite_link',
      activeMembers: 328,
    },
  ],
  plans: [
    {
      id: 1,
      name: 'Free',
      description: 'Community updates and public events.',
      priceCents: 0,
      stars: 0,
      currency: 'XTR',
      interval: 'free',
      status: 'active',
      subscribers: 142,
    },
    {
      id: 2,
      name: 'Pro',
      description: 'Premium group, recordings, and weekly office hours.',
      priceCents: 2900,
      stars: 299,
      currency: 'XTR',
      interval: 'month',
      status: 'active',
      subscribers: 186,
    },
    {
      id: 3,
      name: 'Founder',
      description: 'Private founder calls, templates, and early access.',
      priceCents: 9900,
      stars: 999,
      currency: 'XTR',
      interval: 'month',
      status: 'draft',
      subscribers: 18,
    },
  ],
  referrals: [
    { id: 1, referrer: 'mira', referralCode: 'co_1_2', status: 'activated', clicks: 18, invites: 7, joins: 4, purchases: 2, revenueCents: 8700 },
    { id: 2, referrer: 'deepa', referralCode: 'co_1_1', status: 'joined', clicks: 43, invites: 15, joins: 11, purchases: 6, revenueCents: 17400 },
  ],
  referralCampaigns: [
    {
      id: 1,
      title: 'Invite 3 builders',
      reward: 'Unlock bonus founder call',
      status: 'active',
      clicks: 118,
      joins: 42,
      purchases: 14,
      revenueCents: 40600,
    },
    {
      id: 2,
      title: 'ChallengeHub alumni',
      reward: 'Founding Member badge',
      status: 'draft',
      clicks: 32,
      joins: 9,
      purchases: 3,
      revenueCents: 8700,
    },
  ],
  rewards: [
    { id: 1, type: 'badge', title: 'Founding Member', description: 'Awarded to the first 100 active members.', claimed: true },
    { id: 2, type: 'premium_access', title: 'Referral Unlock', description: 'Invite 3 members to unlock bonus sessions.', claimed: false },
    { id: 3, type: 'certificate', title: 'Ship Week Finisher', description: 'Complete one launch sprint inside the community.', claimed: false },
  ],
  rewardRules: [
    { id: 1, title: 'Daily contribution', trigger: 'Post one useful update', reward: '+20 XP', status: 'active' },
    { id: 2, title: 'Referral activation', trigger: 'Friend buys Pro plan', reward: '+250 XP and bonus call', status: 'active' },
    { id: 3, title: 'Founder badge', trigger: 'Join before public launch', reward: 'Founding Member badge', status: 'draft' },
  ],
  activity: [
    { id: 1, title: 'Pro plan renewed by @mira', eventType: 'subscription', createdAt: new Date(now - 1000 * 60 * 20).toISOString() },
    { id: 2, title: '@sam joined from ChallengeHub', eventType: 'member_joined', createdAt: new Date(now - 3600000).toISOString() },
    { id: 3, title: 'AI report generated 5 suggestions', eventType: 'ai_report', createdAt: new Date(now - 3600000 * 4).toISOString() },
  ],
  accessLogs: [
    { id: 1, action: 'grant', status: 'success', message: 'Invite link issued to @mira', createdAt: new Date(now - 1000 * 60 * 30).toISOString() },
    { id: 2, action: 'sync', status: 'failed', message: 'Missing admin permission for Builder Circle Updates', createdAt: new Date(now - 3600000).toISOString() },
    { id: 3, action: 'renewal', status: 'pending', message: '@sam trial access needs review', createdAt: new Date(now - day).toISOString() },
  ],
  ai: {
    healthScore: 82,
    weeklyReportStatus: 'ready',
    faqCount: 18,
    suggestions: [
      { id: 1, title: 'Welcome message can be tighter', detail: 'New members ask the same setup question in the first 10 minutes.', tone: 'info' },
      { id: 2, title: 'Office hours are driving retention', detail: 'Members who attend one event are 2.4x more likely to renew.', tone: 'ok' },
    ],
  },
  events: [
    { id: 1, title: 'Weekly Founder AMA', type: 'ama', startsAt: new Date(now + day * 2).toISOString(), registrations: 82, priceStars: 0 },
    { id: 2, title: 'AI Builder Sprint', type: 'challenge', startsAt: new Date(now + day * 8).toISOString(), registrations: 41, priceStars: 199 },
  ],
  products: [
    { id: 1, title: 'Launch Checklist', type: 'download', status: 'active', purchases: 24, priceStars: 99 },
    { id: 2, title: 'Private Review Call', type: 'consultation', status: 'active', purchases: 6, priceStars: 599 },
    { id: 3, title: 'Premium Onboarding Vault', type: 'premium_content', status: 'draft', purchases: 0, priceStars: 299 },
  ],
}

export const demoMemberProfile: MemberProfileDto = {
  community: demoDashboard.community,
  member: demoDashboard.members[1],
  referralLink: 'https://t.me/communityos_bot?start=co_1_2',
  rewards: demoDashboard.rewards,
  referralCampaigns: demoDashboard.referralCampaigns.map((campaign) => ({
    ...campaign,
    current: 2,
    claimable: false,
  })),
  events: demoDashboard.events,
  products: demoDashboard.products,
  activity: demoDashboard.activity,
}

export const demoAdminDashboard: AdminDashboardDto = {
  metrics: {
    communities: 24,
    publishers: 19,
    monthlyStars: 84210,
    paymentsCents: 2489000,
    accessFailures: 7,
    aiRequests: 1864,
  },
  communities: [
    { ...demoDashboard.community, owner: '@deepa', members: 328, revenueCents: 412900, healthScore: 82 },
    { id: 2, name: 'AI Operators', handle: '@aioperators', description: 'Automation operators community.', status: 'active', owner: '@mira', members: 914, revenueCents: 1184000, healthScore: 91 },
    { id: 3, name: 'SEO Sprint Club', handle: '@seosprint', description: 'Execution community for SEO builders.', status: 'review', owner: '@nora', members: 144, revenueCents: 147000, healthScore: 68 },
  ],
  payments: [
    { id: 1, community: 'Builder Circle', buyer: '@mira', stars: 299, status: 'paid', createdAt: new Date(now - 1000 * 60 * 22).toISOString() },
    { id: 2, community: 'AI Operators', buyer: '@ren', stars: 999, status: 'paid', createdAt: new Date(now - 3600000 * 3).toISOString() },
    { id: 3, community: 'SEO Sprint Club', buyer: '@nora', stars: 199, status: 'pending', createdAt: new Date(now - 3600000 * 6).toISOString() },
  ],
  issues: [
    { id: 1, title: 'Bot missing ban-user permission', community: 'Builder Circle', severity: 'high', status: 'open' },
    { id: 2, title: 'Stars pre-checkout retry spike', community: 'AI Operators', severity: 'medium', status: 'watching' },
    { id: 3, title: 'Weekly AI report skipped', community: 'SEO Sprint Club', severity: 'low', status: 'queued' },
  ],
}
